version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-react
    versions:
    - 7.21.5
  - dependency-name: elliptic
    versions:
    - 6.5.3
